/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UDetalles.java
 *
 * Created on 21/05/2010, 09:15:25 AM
 */

package pcortesgui;

import javax.swing.JTable;
import javax.swing.table.*;
import java.awt.*;

import edatos.*;


/**
 *
 * @author ealonso
 */
public class UDetalles extends javax.swing.JDialog {

    /** Creates new form UDetalles */
    public UDetalles(java.awt.Frame parent, boolean modal, TLista S ) {
        super(parent, modal);
        initComponents();

        //JTableHeader H = this.jTCortes.getTableHeader();
        int i;

        //TableColumnModel columnModel;

        //jTCortes.setco.setColumnModel(columnModel);


        TableColumn column = null;

        for (i = 0; i < jTCortes.getColumnCount(); i++) {
            column = jTCortes.getColumnModel().getColumn(i);
            column.setPreferredWidth(10);
            column = jTSob.getColumnModel().getColumn(i);
            column.setPreferredWidth(10);
            
            //column.setp
        }

        if ( S == null || S.Vacia() )
            return;
        
        int filas;
        filas = S.Cantidad()-1;

        Object [][] model = new String[filas][5];
        String [] headers = new String[5];
        headers[0] = "Nro";
        headers[1] = "Alto";
        headers[2] = "Ancho";
        headers[3] = "X";
        headers[4] = "Y";

        for ( i = 0; i < filas; i++ )
        {
            TRectangulo R = ((TNodoAB)S.Obtener(i)).estado.RC;
            model[i][0] = String.valueOf(i+1);
            model[i][1] = String.valueOf(R.obtLargo());
            model[i][2] = String.valueOf(R.obtAncho());
            model[i][3] = String.valueOf(R.obtX());
            model[i][4] = String.valueOf(R.obtY());
        }
        jTCortes.setModel(new javax.swing.table.DefaultTableModel(
            model, headers
            ));
        if ( i > 0 )
        {
           TLista D = ((TNodoAB)S.Obtener(i)).estado.L;
           filas = D.Cantidad();
           model = new String[filas][5];
           headers = new String[5];
           headers[0] = "Nro";
           headers[1] = "Alto";
           headers[2] = "Ancho";
           headers[3] = "X";
           headers[4] = "Y";
           for ( i = 0; i < filas; i++ ) {
             TRectangulo R=(TRectangulo)D.Obtener(i);
             model[i][0] = String.valueOf(i+1);
             model[i][1] = String.valueOf(R.obtLargo());
             model[i][2] = String.valueOf(R.obtAncho());
             model[i][3] = String.valueOf(R.obtX());
             model[i][4] = String.valueOf(R.obtY());
           }
           jTSob.setModel(new javax.swing.table.DefaultTableModel(
            model, headers
            ));
        }


        
    }




    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTCortes = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTSob = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(pcortesgui.PcortesguiApp.class).getContext().getResourceMap(UDetalles.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setModal(true);
        setName("Form"); // NOI18N
        setResizable(false);

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTCortes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nro", "Alto", "Ancho", "X", "Y"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTCortes.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTCortes.setName("jTCortes"); // NOI18N
        jTCortes.setRowSelectionAllowed(false);
        jTCortes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTCortes.getTableHeader().setResizingAllowed(false);
        jTCortes.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTCortes);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setName("jScrollPane2"); // NOI18N

        jTSob.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nro", "Alto", "Ancho", "X", "Y"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTSob.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTSob.setName("jTSob"); // NOI18N
        jTSob.setRowSelectionAllowed(false);
        jTSob.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTSob.getTableHeader().setResizingAllowed(false);
        jTSob.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTSob);

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(187, 187, 187)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(271, 271, 271)
                        .addComponent(jButton1)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, 0, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UDetalles dialog = new UDetalles(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTCortes;
    private javax.swing.JTable jTSob;
    // End of variables declaration//GEN-END:variables

}
